/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplikasi;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mila Oktaviani
 */
public class pelanggan extends javax.swing.JFrame {

    /**
     * Creates new form pelanggan
     */
    
    private DefaultTableModel model2;
    private int selectpelanggan;
    String idpelanggan, namapelanggan, jk, tempatlahir, tanggallahir, alamat, nohp;
    public pelanggan() {
        initComponents();
        
        model2 = new DefaultTableModel();
        ModelPelanggan.setModel(model2);
        model2.addColumn("Id Pelanggan");
        model2.addColumn("Nama Pelanggan");
        model2.addColumn("Alamat");
        model2.addColumn("No Telpon");
        
        GetData();
    }
    
    public pelanggan(DefaultTableModel model) {
        this.model2 = model2;
    }

    public DefaultTableModel getTableModel() {
        return model2;
    }
    
    public void GetData(){
        model2.getDataVector().removeAllElements();
        model2.fireTableDataChanged();
        try {
            Statement st = (Statement)koneksi.koneksiDB().createStatement();
            String sql ="select * from tbpelanggan";
            ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()){
                Object[] obj = new Object[4];
                obj[0] = rs.getString("idpelanggan");
                obj[1] = rs.getString("namapelanggan");
                obj[2] = rs.getString("alamat");
                obj[3] = rs.getString("nohp");
                
                model2.addRow(obj);
            }
    }catch (SQLException error){
        JOptionPane.showMessageDialog(null, error.getMessage());  
        }
    }
    
    public void selectpelanggan() {
        selectpelanggan = ModelPelanggan.getSelectedRow();
        if (selectpelanggan != -1) {
            frmPembayaran frmPembayaran = new frmPembayaran();
            frmPembayaran.setPelanggan(this);
            frmPembayaran.setVisible(true);
            frmPembayaran.selectpelanggan();
//            frmPembayaran.aktif();
            this.setVisible(false);
        }else {
            JOptionPane.showMessageDialog(null, "Terdapat Error saat memilih data!");
        }
    }
    
    public int select2() {
        return selectpelanggan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ModelPelanggan = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ModelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ModelPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModelPelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ModelPelanggan);

        jButton1.setText("OK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ModelPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModelPelangganMouseClicked
        // TODO add your handling code here:
        selectpelanggan();
    }//GEN-LAST:event_ModelPelangganMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        //        if(caller.equalsIgnoreCase("Transaksi")){
            //            int row = ModelBarang.getSelectedRow();
            //            String kode = ModelBarang.getValueAt(row, 0).toString();
            //            String nama = ModelBarang.getValueAt(row, 1).toString();
            //            int stok = Integer.parseInt(ModelBarang.getValueAt(row, 2).toString());
            //            int harga = Integer.parseInt(ModelBarang.getValueAt(row, 3).toString());
            //
            //            Transaksi.txkode.setText(kode);
            //            Transaksi.txnama.setText(nama);
            //            Transaksi.harga = harga;
            //            Transaksi.stok = stok;
            //            Transaksi.txqty.setEditable(true);
            //            Transaksi.btnSimpan.setEnabled(true);
            //            Transaksi.txqty.requestFocus();
            //            dispose();
            //        }else if(caller.equalsIgnoreCase("Pelanggan")){
            //            int row = ModelBarang.getSelectedRow();
            //            String id = ModelBarang.getValueAt(row, 0).toString();
            //            String nama = ModelBarang.getValueAt(row, 1).toString();
            //            Transaksi.txidPelanggan.setText(id);
            //            Transaksi.txpelanggan.setText(nama);
            //            dispose();
            //        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ModelPelanggan;
    public static javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
